using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatINoted.Models
{
    /// <summary>
    /// NotebookModel stores information representing a Notebook.
    /// </summary>
    public class NotebookModel
    {
        /// <summary>
        /// Title of the book.
        /// </summary>
        private String Title { get; set; }

        /// <summary>
        /// Author of the book.
        /// </summary>
        private String Author { get; set; }

        /// <summary>
        /// ISBN of the book.
        /// </summary>
        private IsbnModel Isbn { get; set; }

        /// <summary>
        /// List of Notes filed under the book.
        /// </summary>
        private List<NoteModel> Notes { get; set; }

        /// <summary>
        /// Unique id generated by Firebase.
        /// </summary>
        private String Id { get; set; }

        /// <summary>
        /// Construct an empty NotebookModel.
        /// </summary>
        public NotebookModel()
        {
            this.Title = "";
            this.Author = "";
            this.Isbn = null;
            this.Notes = new List<NoteModel>();
            this.Id = "";
        }

        /// <summary>
        /// Construct a NotebookModel with the given characteristics.
        /// </summary>
        /// <param name="Title">notebook title</param>
        /// <param name="Author">notebook author</param>
        /// <param name="Isbn">ISBN</param>
        /// <param name="Notes">list of attached notes</param>
        /// <param name="Id">unique firebase id</param>
        public NotebookModel(String Title, String Author, IsbnModel Isbn, List<NoteModel> Notes, String Id)
        {
            this.Title = Title;
            this.Author = Author;
            this.Isbn = Isbn;
            this.Notes = Notes;
            this.Id = Id;
        }
    }
}