//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatINoted {
	
	
	public partial class CreateEditNoteView {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.UpdatePanel AddNoteUpdatePanel;
		
		protected System.Web.UI.WebControls.DropDownList NotebookList;
		
		protected System.Web.UI.WebControls.HiddenField HandleLoginUserID;
	}
}
