//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatINoted {
	
	
	public partial class NotesView {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.UpdatePanel LoginUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NotebookTitle;
		
		protected System.Web.UI.WebControls.Table NotesTable;
		
		protected System.Web.UI.WebControls.HiddenField NoteID;
		
		protected System.Web.UI.WebControls.HiddenField HandleLoginUserID;
	}
}
